background {
    monitor = 
    path = ~/.local/wallpapers/lofi_cafe.jpg
    blur_passes = 2
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spaceing = 0.35
    dots_center = false
    outer_color = rgba(0,0,0,0.2)
    inner_color = rgba(0,0,0,0.2)
    hide_input = false
    fade_on_empty = false
    check_color = rgb(179, 140, 82)
    font_color = rgb(202, 202, 202)
    fail_color = rgb(207, 97, 97)
    placeholder_text = <i><span foreground="##9a9a9a">Password</span></i>
    fail_text = <i>Bruh... <b>($ATTEMPTS)</b></i>
}